# Test your FastAPI endpoints

GET http://127.0.0.1:8000/read/?address=https://pupper.cn/posts/b3426ccb.html
Accept: application/json

###

POST http://127.0.0.1:8000/insert/
Content-Type: application/json

{"address":"https://pupper.cn/posts/b3426ccb.html","ip":"127.0.0.12","view":"view4"}
###